/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifrn.edu.projeto;

import br.ifrn.edu.conexao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Netollyno
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
        iniciar();
    }

    private void iniciar() {
        todosLivros();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblValor.setVisible(false);
        txtValor.setVisible(false);
        lblCateg.setVisible(false);
        cbCateg.setVisible(false);

        alinhaTable();
    }

    private void alinhaTable() {
        DefaultTableCellRenderer centerCol = new DefaultTableCellRenderer();
        centerCol.setHorizontalAlignment(SwingConstants.CENTER);
        tblLivros.getColumnModel().getColumn(0).setCellRenderer(centerCol);
        tblLivros.getColumnModel().getColumn(3).setCellRenderer(centerCol);

        JTableHeader header = tblLivros.getTableHeader();
        DefaultTableCellRenderer centerTitle = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centerTitle.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        painelBusca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lblCateg = new javax.swing.JLabel();
        cbCateg = new javax.swing.JComboBox<>();
        btnBusca = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Virtual");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Editora", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblLivrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLivros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 398, 867, 225));

        painelBusca.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Livros");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tipo busca:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Código", "Título", "Editora", "Categoria" }));
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });

        lblCateg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCateg.setText("Categoria:");

        cbCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Conto", "Crônica", "Drama", "Ficção", "Memórias" }));

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        txtValor.setPreferredSize(new java.awt.Dimension(63, 26));

        lblValor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValor.setText("Valor:");

        javax.swing.GroupLayout painelBuscaLayout = new javax.swing.GroupLayout(painelBusca);
        painelBusca.setLayout(painelBuscaLayout);
        painelBuscaLayout.setHorizontalGroup(
            painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscaLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBuscaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBuscaLayout.createSequentialGroup()
                        .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelBuscaLayout.createSequentialGroup()
                                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelBuscaLayout.createSequentialGroup()
                                .addComponent(lblCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))))
            .addGroup(painelBuscaLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBuscaLayout.setVerticalGroup(
            painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCateg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnBusca)
                .addGap(29, 29, 29))
        );

        jPanel1.add(painelBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 12, -1, -1));

        jMenu3.setText("Sistema");

        jMenu2.setText("Atualizar");
        jMenu3.add(jMenu2);

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLivrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLivrosKeyPressed

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged
        // TODO add your handling code here:
        if (cbTipo.getSelectedIndex() == 0) {
            txtValor.setVisible(false);
            lblValor.setVisible(false);
            lblCateg.setVisible(false);
            cbCateg.setVisible(false);
            todosLivros();
        } else if (cbTipo.getSelectedIndex() != 4) {
            txtValor.setVisible(true);
            txtValor.setText("");
            lblValor.setVisible(true);
            lblValor.setText(cbTipo.getSelectedItem() + ":");
            lblCateg.setVisible(false);
            cbCateg.setVisible(false);
        } else {
            txtValor.setVisible(false);
            lblValor.setVisible(false);
            lblCateg.setVisible(true);
            cbCateg.setVisible(true);
        }
    }//GEN-LAST:event_cbTipoItemStateChanged

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        if (cbTipo.getSelectedIndex() == 1) {
            if (!txtValor.getText().trim().isEmpty()) {
                int cod = Integer.parseInt(txtValor.getText());

                codLivros(cod);
            } else {
                JOptionPane.showMessageDialog(null, "Campo código sem valor!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (cbTipo.getSelectedIndex() == 2) {
            if (!txtValor.getText().trim().isEmpty()) {
                String titulo = txtValor.getText();

                tituloLivros(titulo);
            } else {
                JOptionPane.showMessageDialog(null, "Campo código sem valor!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (cbTipo.getSelectedIndex() == 3) {
            if (!txtValor.getText().trim().isEmpty()) {
                String editora = txtValor.getText();

                editoraLivros(editora);
            } else {
                JOptionPane.showMessageDialog(null, "Campo código sem valor!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (cbTipo.getSelectedIndex() == 4) {
            if (cbCateg.getSelectedIndex() != 0) {
                String categoria = cbCateg.getSelectedItem() + "";

                categoriaLivros(categoria);
            } else {
                todosLivros();
            }
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.out.println("Era pra sair");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formatarTabela() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void formatarCampos() {
        try {
            txtValor.setText("");
            txtValor.grabFocus();
        } catch (Exception e) {
            System.out.println("ERRO:" + e.getMessage());
        }
    }

    private void todosLivros() {
        formatarTabela();

        try {
            Connection conn = Conexao.getConnection();
            String command = "SELECT * FROM LIVRO "
                    + "ORDER BY COD_UNICO";

            PreparedStatement ps = conn.prepareStatement(command);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (rs.next()) {
                String[] linhaLivro = new String[]{
                    rs.getString("COD_UNICO"),
                    rs.getString("TITULO"),
                    rs.getString("EDITORA"),
                    rs.getString("CATEGORIA")
                };
                dtm.addRow(linhaLivro);
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    

    private void codLivros(int cod) {
        formatarTabela();

        try {
            Connection conn = Conexao.getConnection();
            String command = "SELECT * FROM LIVRO "
                    + " WHERE COD_UNICO = ?";

            PreparedStatement ps = conn.prepareStatement(command);
            ps.setInt(1, cod);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (rs.next()) {
                String[] linhaLivro = new String[]{
                    rs.getString("COD_UNICO"),
                    rs.getString("TITULO"),
                    rs.getString("EDITORA"),
                    rs.getString("CATEGORIA")
                };
                dtm.addRow(linhaLivro);
            }

            formatarCampos();

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void tituloLivros(String titulo) {
        formatarTabela();

        try {
            Connection conn = Conexao.getConnection();
            String command = "SELECT * FROM LIVRO "
                    + " WHERE TITULO LIKE ?";

            PreparedStatement ps = conn.prepareStatement(command);
            ps.setString(1, "%" + titulo + "%");

            ResultSet rs = ps.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (rs.next()) {
                String[] linhaLivro = new String[]{
                    rs.getString("COD_UNICO"),
                    rs.getString("TITULO"),
                    rs.getString("EDITORA"),
                    rs.getString("CATEGORIA")
                };
                dtm.addRow(linhaLivro);
            }

            formatarCampos();

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void editoraLivros(String categora) {
        formatarTabela();

        try {
            Connection conn = Conexao.getConnection();
            String command = "SELECT * FROM LIVRO "
                    + " WHERE CATEGORIA = ?";

            PreparedStatement ps = conn.prepareStatement(command);
            ps.setString(1, categora);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (rs.next()) {
                String[] linhaLivro = new String[]{
                    rs.getString("COD_UNICO"),
                    rs.getString("TITULO"),
                    rs.getString("EDITORA"),
                    rs.getString("CATEGORIA")
                };
                dtm.addRow(linhaLivro);
            }

            formatarCampos();

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void categoriaLivros(String categora) {
        formatarTabela();

        try {
            Connection conn = Conexao.getConnection();
            String command = "SELECT * FROM LIVRO "
                    + " WHERE CATEGORIA = ?";

            PreparedStatement ps = conn.prepareStatement(command);
            ps.setString(1, categora);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tblLivros.getModel();

            while (rs.next()) {
                String[] linhaLivro = new String[]{
                    rs.getString("COD_UNICO"),
                    rs.getString("TITULO"),
                    rs.getString("EDITORA"),
                    rs.getString("CATEGORIA")
                };
                dtm.addRow(linhaLivro);
            }

            formatarCampos();

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JComboBox<String> cbCateg;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCateg;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel painelBusca;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
